### ISSUE TITLE
fatal error: auxiliary_compat.h: No such file or directory

### ISSUE THREAD

**Issue by GermanAizek** [intel/ethernet-linux-ixgbe#7]
@aloktion, previous build error has not been fixed in new release.

Debian sid (Testing)
Linux Kernel 6.12.3

```
*** The target kernel has CONFIG_MODULE_SIG_ALL enabled, but
*** the signing key cannot be found. Module signing has been
*** disabled for this build.
make[1]: Entering directory '/usr/src/linux-headers-6.12.3-common'
make[2]: Entering directory '/usr/src/linux-headers-6.12.3-amd64'
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_main.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_api.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_common.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82598.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82599.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_ethtool.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_lib.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_mbx.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_sriov.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_param.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_phy.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_procfs.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_xsk.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82598.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82599.o
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x540.o
make[4]: *** No rule to make target '/home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_e610.o', needed by '/home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.o'.  Stop.
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x550.o
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_ethtool.c:18:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.                                                                                                                                                                                           
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82598.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_common.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_common.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82599.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82598.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x540.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x540.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_mbx.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_api.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_api.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_sriov.c:15:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x550.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x550.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_ethtool.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_sriov.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_common.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82598.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82599.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x540.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_api.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_82598.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_x550.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_mbx.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_xsk.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_main.c:31:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_xsk.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_param.c:7:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_procfs.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_main.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_procfs.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_param.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_api.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_phy.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_phy.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82599.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb_82599.o] Error 1
In file included from /home/debian/GIT/ethernet-linux-ixgbe/src/kcompat.h:7008,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_osdep.h:16,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_type.h:45,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_dcb.h:7,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe.h:24,
                 from /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_lib.c:4:
/home/debian/GIT/ethernet-linux-ixgbe/src/kcompat_impl.h:43:10: fatal error: auxiliary_compat.h: No such file or directory
   43 | #include "auxiliary_compat.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/src/linux-headers-6.12.3-common/scripts/Makefile.build:234: /home/debian/GIT/ethernet-linux-ixgbe/src/ixgbe_lib.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.12.3-common/Makefile:1961: /home/debian/GIT/ethernet-linux-ixgbe/src] Error 2
make[2]: *** [/usr/src/linux-headers-6.12.3-common/Makefile:236: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.12.3-amd64'
make[1]: *** [Makefile:236: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.3-common'
make: *** [Makefile:107: default] Error 2
```

**Comment by c-po** [comment]
https://github.com/intel/ethernet-linux-ixgbe/releases/tag/v6.0.5 latest release works on my end using 6.6.77
